version = 1

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "scala"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "php"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/aseem-deepsource/Gigarepo"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "black"

[[transformers]]
name = "yapf"

[[transformers]]
name = "gofumpt"

[[transformers]]
name = "gofmt"

[[transformers]]
name = "isort"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "rubocop"

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"

[[transformers]]
name = "standardrb"

[[transformers]]
name = "google-java-format"

[[transformers]]
name = "php-cs-fixer"

[[transformers]]
name = "rustfmt"

[[transformers]]
name = "dotnet-format"